"""add rejection reason to bookings

Revision ID: 08a36550bb7c
Revises: f5e42bd7c39d
Create Date: 2026-08-13 23:08:12.271750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a36550bb7c'
down_revision: Union[str, Sequence[str], None] = 'f5e42bd7c39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'rejection_reason')
    # ### end Alembic commands ###
