"""add rejected booking status

Revision ID: 0dce7529a4e0
Revises: 08a36550bb7c
Create Date: 2026-08-14 11:34:03.953874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0dce7529a4e0'
down_revision: Union[str, Sequence[str], None] = '08a36550bb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'status',
               existing_type=mysql.ENUM('PENDING', 'ACCEPTED', 'COMPLETED', 'CANCELLED'),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'COMPLETED', 'REJECTED', name='bookingstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'COMPLETED', 'REJECTED', name='bookingstatus'),
               type_=mysql.ENUM('PENDING', 'ACCEPTED', 'COMPLETED', 'CANCELLED'),
               existing_nullable=False)
    # ### end Alembic commands ###
